True parallel ptrace, part 3
Fixed bug: For every child process, bash will notice the process is
stopped upon startup, and will print `[id]+ Stopped`. This doesn't
indicate failure to launch process. However, it messes up terminal
outputs very quickly

New bug: git pull fails to waitpid:
```
anon@penguin:~/proot-rust$ git pull
error: waitpid is confused (rev-list)
error: waitpid is confused (ssh)
error: waitpid is confused (gc)
error: waitpid is confused (fetch)
```

Maybe fix this by returning EINTR instead of 0